fanfic_project/fanfic/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_fanfic, name='create_fanfic'),
    path('my_fanfics/', views.my_fanfics, name='my_fanfics'),
    path('fanfic/<int:pk>/', views.fanfic_detail, name='fanfic_detail'),
    path('fanfic/<int:pk>/delete/', views.delete_fanfic, name='delete_fanfic'),
    path('fanfic/<int:pk>/rate/', views.increase_rating, name='increase_rating'),
    path('fanfic/<int:fanfic_pk>/chapter/<int:chapter_pk>/', views.chapter_detail, name='chapter_detail'),
    path('search/', views.search_fanfics, name='search_fanfics'),
    path('search/results/', views.search_results, name='search_results'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

handler404 = 'fanfic.views.handler404'
handler500 = 'fanfic.views.handler500'

fanfic_project/fanfic_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('fanfic.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fanfic_project/fanfic/models.py
from django.db import models
from django.contrib.auth.models import User

class Fanfic(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=400)
    content = models.TextField(default='Текст фанфика будет здесь.')
    rating = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='fanfic_images/')
    tags = models.CharField(default='Гарем, Юри', max_length=400)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.title

class Chapter(models.Model):
    fanfic = models.ForeignKey(Fanfic, related_name='chapters', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return self.title

fanfic_project/fanfic/forms.py
from django import forms
from .models import Fanfic

class FanficForm(forms.ModelForm):
    class Meta:
        model = Fanfic
        fields = ['title', 'description', 'content', 'image', 'tags']
        widgets = {
            'content ': forms.Textarea(attrs={'rows':1, 'cols':1}),
        }

    def __init__(self, *args, **kwargs):
        super(FanficForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

class SearchForm(forms.Form):
    query = forms.CharField(label='Поиск по тегам', max_length=100)

fanfic_project/fanfic/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Fanfic, Chapter
from .forms import FanficForm, SearchForm
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.template import RequestContext

def home(request):
    fanfics = Fanfic.objects.all()[:10]
    return render(request, 'fanfic/home.html', {'fanfics': fanfics})

@login_required
def create_fanfic(request):
    if request.method == 'POST':
        form = FanficForm(request.POST, request.FILES)
        if form.is_valid():
            fanfic = form.save(commit=False)
            fanfic.user = request.user
            fanfic.save()

            # Разбиение описания на главы по 1000 символов
            content = fanfic.content
            chapters = [content[i:i + 1000] for i in range(0, len(content), 1000)]
            for i, chapter_content in enumerate(chapters):
                Chapter.objects.create(fanfic=fanfic, title=f'Глава {i + 1}', content=chapter_content)

            return redirect('my_fanfics')
    else:
        form = FanficForm()
    return render(request, 'fanfic/create_fanfic.html', {'form': form})

@login_required
def my_fanfics(request):
    fanfics = Fanfic.objects.filter(user=request.user)
    return render(request, 'fanfic/my_fanfics.html', {'fanfics': fanfics})

def fanfic_detail(request, pk):
    fanfic = get_object_or_404(Fanfic, pk=pk)
    return render(request, 'fanfic/fanfic_detail.html', {'fanfic': fanfic})

def chapter_detail(request, fanfic_pk, chapter_pk):
    fanfic = get_object_or_404(Fanfic, pk=fanfic_pk)
    chapter = get_object_or_404(Chapter, pk=chapter_pk)
    chapters = list(fanfic.chapters.all())
    current_index = chapters.index(chapter)
    prev_chapter = chapters[current_index - 1] if current_index > 0 else None
    next_chapter = chapters[current_index + 1] if current_index < len(chapters) - 1 else None
    context = {
        'fanfic': fanfic,
        'chapter': chapter,
        'prev_chapter': prev_chapter,
        'next_chapter': next_chapter,
    }
    return render(request, 'fanfic/chapter_detail.html', context)


def increase_rating(request, pk):
    fanfic = get_object_or_404(Fanfic, pk=pk)
    fanfic.rating += 1
    fanfic.save()
    return redirect('fanfic_detail', pk=pk)

@login_required
def delete_fanfic(request, pk):
    fanfic = get_object_or_404(Fanfic, pk=pk)
    if fanfic.user == request.user:
        fanfic.delete()
    return redirect('my_fanfics')

def search_fanfics(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            fanfics = Fanfic.objects.filter(tags__icontains=query)
            return render(request, 'fanfic/search_results.html', {'fanfics': fanfics})
    else:
        form = SearchForm()
    return render(request, 'fanfic/search_fanfics.html', {'form': form})

def search_results(request):
    query = request.GET.get('q')
    fanfics = Fanfic.objects.filter(tags__icontains=query)
    return render(request, 'fanfic/search_results.html', {'fanfics': fanfics})

def contact(request):
    if request.method == 'POST':
        message_name = request.POST['name']
        message_email = request.POST['email']
        message = request.POST['message']

        send_mail(
            'Сообщение с сайта',
            message,
            message_email,
            ['nidedno@gmail.com'],
        )

        return render(request, 'fanfic/contact.html', {'message_name': message_name})
    else:
        return render(request, 'fanfic/contact.html')

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

def logout_view(request):
    logout(request)
    return render(request, 'registration/logout_confirm.html')

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'registration/login.html', {'form': form})

def handler404(request, exception):
    response = render('404.html', {},
                              context_instance=RequestContext(request))
    response.status_code = 404
    return render(request, '404.html')

def handler500(request):
    response = render('500.html', {},
                              context_instance=RequestContext(request))
    response.status_code = 500
    return render(request, '500.html')

fanfic_project/templates/fanfic/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Fanfic Site{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static 'fanfic/style.css' %}">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">Фанфики</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create_fanfic' %}">Создать</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'my_fanfics' %}">Библиотека</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'search_fanfics' %}">Поиск</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}">Обратная связь</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Войти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'signup' %}">Регистрация</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

fanfic_project/templates/fanfic/chapter_detail.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="mt-4">
    <h2>{{ chapter.title }}</h2>
    <p>{{ chapter.content }}</p>
    <div class="d-flex justify-content-between mt-4">
        {% if prev_chapter %}
        <a href="{% url 'chapter_detail' fanfic.pk prev_chapter.pk %}" class="btn btn-dark">Назад</a>
        {% else %}
        <button class="btn btn-secondary" disabled>Назад</button>
        {% endif %}
        <a href="{% url 'fanfic_detail' fanfic.pk %}" class="btn btn-dark">К фанфику</a>
        {% if next_chapter %}
        <a href="{% url 'chapter_detail' fanfic.pk next_chapter.pk %}" class="btn btn-dark">Вперед</a>
        {% else %}
        <button class="btn btn-secondary" disabled>Вперед</button>
        {% endif %}
    </div>
</div>
{% endblock %}

fanfic_project/templates/fanfic/contact.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="mt-4">
    <h2>Обратная связь</h2>
    <form method="post" class="mt-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_name" class="form-label">Ваше имя:</label>
            <input type="text" name="name" id="id_name" class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_email" class="form-label">Ваш email:</label>
            <input type="email" name="email" id="id_email" class="form-control">
        </div>
        <div class="mb-3">
            <label for="id_message" class="form-label">Сообщение:</label>
            <textarea name="message" id="id_message" class="form-control" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-dark">Отправить</button>
    </form>
</div>
{% endblock %}

fanfic_project/templates/fanfic/create_fanfic.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="mt-4 mb-4">
    <h2 class="text-center">Создать фанфик</h2>
    <form method="post" enctype="multipart/form-data" class="mt-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label"><b>Название:</b></label>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="id_description" class="form-label"><b>Описание:</b></label>
            {{ form.description }}
        </div>
        <div class="mb-3">
            <label for="id_content" class="form-label"><b>Контент:</b></label>
            {{ form.content }}
        </div>
        <div class="mb-3">
            <label for="id_tags" class="form-label"><b>Теги:</b></label>
            {{ form.tags }}
        </div>
        <div class="mb-3">
            <label for="id_image" class="form-label"><b>Изображение:</b</label>
            {{ form.image }}
        </div>
        <button type="submit" class="btn btn-dark">Создать</button>
    </form>
</div>
{% endblock %}

fanfic_project/templates/fanfic/fanfic_detail.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="row mt-4">
    <h2 class="text-center mb-4">{{fanfic.title}}</h2>
    <!-- Левая колонка с деталями фанфика -->
    <div class="col-md-4 rounded border">
        <div class="row g-2 mt-4">
            {% if fanfic.image %}
            <img src="{{ fanfic.image.url }}" class="col-2 rounded-circle" alt="{{ fanfic.title }}" style="width: 150px; height: 150px;">
            {% endif %}
            <h4 class="col-5">{{ fanfic.title }}</h4>
        </div>
        <div class="mt-3">
            <p><strong>Описание:</strong> {{ fanfic.description }}</p>
            <p><strong>Тэги:</strong> {{ fanfic.tags }}</p>
            <p><strong>Автор:</strong> {{ fanfic.user }}</p>
            <p><strong>Лайков:</strong> {{ fanfic.rating }}</p>
        </div>
        <form method="post" action="{% url 'increase_rating' fanfic.pk %}" class="mt-3 mb-3">
            {% csrf_token %}
            <button type="submit" class="btn btn-dark">Нравится</button>
        </form>
    </div>
    
    <!-- Правая колонка со списком глав -->
    <div class="col-md-8">
        <h3 class="text-center">Главы</h3>
        <ul class="row">
            {% for chapter in fanfic.chapters.all %}
            <li class="list-group-item" style="width: 100px; height: 45px;">
                <a href="{% url 'chapter_detail' fanfic.pk chapter.pk %}" class="btn btn-dark">{{ chapter.title }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

fanfic_project/templates/fanfic/home.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="container mt-4 d-flex justify-content-center">
    <div class="row">
        <h2 class="text-center">Последние фанфики</h2>
        {% for fanfic in fanfics %}
        <div class="col-12 mb-4">
            <div class="row">
                {% if forloop.counter0|divisibleby:2 %}
                <div class="mb-4 mt-4 row d-flex justify-content-center">
                    <div class="col-md-4">
                        <img src="{{ fanfic.image.url }}" class="img-fluid rounded" alt="{{ fanfic.title }}" style="height: 200px; width:200px;object-fit: cover;">
                    </div>
                    <div class="col-md-4">
                        <h3>{{ fanfic.title }}</h3>
                        <p>{{ fanfic.tags }}</p>
                        <p>Рейтинг: {{ fanfic.rating }}</p>
                        <p>Автор: {{ fanfic.user }}</p>
                        <a href="{% url 'fanfic_detail' fanfic.pk %}" class="btn btn-dark">Читать</a>
                    </div>
                </div>
                {% else %}
                <div class="mb-4 mt-4 row d-flex justify-content-center">
                    <div class="col-md-4 order-md-1 order-2">
                        <h3>{{ fanfic.title }}</h3>
                        <p>{{ fanfic.tags }}</p>
                        <p>Рейтинг: {{ fanfic.rating }}</p>
                        <p>Автор: {{ fanfic.user }}</p>
                        <a href="{% url 'fanfic_detail' fanfic.pk %}" class="btn btn-dark">Читать</a>
                    </div>
                    <div class="col-md-4 order-md-2 order-1">
                        <img src="{{ fanfic.image.url }}" class="img-fluid rounded" alt="{{ fanfic.title }}" style="height: 200px; width:200px ;object-fit: cover;">
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

fanfic_project/templates/fanfic/my_fanfics.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="row mt-4 mb-4">
    <h2 class="text-center mb-4">Мои фанфики</h1>
    {% for fanfic in fanfics %}
    <div class="col-md-6 col-lg-3 mb-4 d-flex align-items-stretch">
        <div class="card rounded">
            {% if fanfic.image %}
            <div class="card-img-container">
                <img src="{{ fanfic.image.url }}" class="card-img" alt="{{ fanfic.title }}">
            </div>
            {% endif %}
            <div class="card-body d-flex flex-column">
                <h5 class="card-title">{{ fanfic.title }}</h5>
                <p class="card-text">{{ fanfic.description }}</p>
                <p class="card-text">Рейтинг: {{ fanfic.rating }}</p>
                <form method="post" action="{% url 'delete_fanfic' fanfic.pk %}" class="mt-2 m-auto">
                    {% csrf_token %}
                    <a href="{% url 'fanfic_detail' fanfic.pk %}" class="btn btn-dark m-auto">Читать</a>
                    <button type="submit" class="btn btn-secondary" onClick='return confirmSubmit()'>Удалить</button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<script LANGUAGE="JavaScript">
    
    function confirmSubmit()
    {
        var agree=confirm("Вы уверены, что хотите удалить фанфик?");
        if (agree)
            return true;
        else
            return false;
    }
</script>
    
{% endblock %}

fanfic_project/templates/fanfic/search_fanfics.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="mt-4">
    <h2 class="text-center">Поиск фанфиков</h2>
    <form method="get" action="{% url 'search_results' %}" class="mt-3">
        <div class="mb-3">
            <label for="search" class="form-label">Введите теги для поиска:</label>
            <input type="text" name="q" id="search" class="form-control">
        </div>
        <button type="submit m-5" class="btn btn-dark">Поиск</button>
    </form>
</div>
{% endblock %}

fanfic_project/templates/fanfic/search_results.html
{% extends 'fanfic/base_generic.html' %}

{% block content %}
<div class="mt-4">
    <h2>Результаты поиска</h2>
    {% if fanfics %}
    <div class="row">
        {% for fanfic in fanfics %}
        <div class="col-md-6 col-lg-3 mb-4 d-flex align-items-stretch">
            <div class="card rounded">
                {% if fanfic.image %}
                <div class="card-img-container">
                    <img src="{{ fanfic.image.url }}" class="card-img" alt="{{ fanfic.title }}">
                </div>
                {% endif %}
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ fanfic.title }}</h5>
                    <p class="card-text">{{ fanfic.description }}</p>
                    <p class="card-text">Рейтинг: {{ fanfic.rating }}</p>
                    <a href="{% url 'fanfic_detail' fanfic.pk %}" class="btn btn-dark m-auto">Читать</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>Ничего не найдено.</p>
    {% endif %}
</div>
{% endblock %}